### ISSUE TITLE
Investigate await

### ISSUE THREAD

**Issue by rcbgr** [jc-cb/prime-workshop-scripts#7]
Check cpu scheduler

**Comment by nmorgan-cb** [comment]
From what I can tell reading documentation, websockets expects to run as a coroutine rather than just an infinite loop. This is why async is required for websockets to run. 

https://websockets.readthedocs.io/en/5.0/intro.html#:~:text=If%20you're%20using%20Python,%3A%20message%20%3D%20yield%20from%20websocket.

The sign function is a coroutine as well and requires await in front of it.
